export const APP_TOGGELE_SIDEBAR = 'APP_TOGGELE_SIDEBAR'
export const AUTH_SET_COOKIE = 'AUTH_SET_COOKIE'
export const USER_SET_COOKIE = 'USER_SET_COOKIE'
export const USER_REMOVE_COOKIE = 'USER_REMOVE_COOKIE'
